package com.example.academiarecommendersystem

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import android.widget.AdapterView
import android.widget.ArrayAdapter
import android.widget.Spinner
import android.widget.Toast
import android.widget.Toast.LENGTH_LONG
import android.widget.Toast.LENGTH_SHORT
import kotlinx.android.synthetic.main.activity_recommendation.*

class Recommendation : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_recommendation)
        val personNames = arrayOf("quality of service support in ieee 802.16 networks", "a unk digital image watermarking scheme resistant to permutation attack", "frequency-domain identification and model-order selection for efficiently simulating microwave unk ", "unk", "an example of communication between security tools : unk - snort ", "prolog for imperative programmers", "uniquely unk colorable graphs","parameter estimation for nonlinear unk , data and parameter uncertainty , and constraints on parameter changes","results on maximal partial spreads in pg ( 3 , p3 ) and on related minihypers"
        ,"unk bitstream generation for h.264/avc decoder conformance test","examination of the effects of degeneration on vertebral artery by using neural network in cases with cervical unk"," to whom am i speaking ?","generalized instantaneous parameters and window matching in unk plane","two matrix inversions associated with the unk formula , their unk and applications","a cellular neural network methodology for deformable object simulation","a runtime profile method for dynamic binary translation using unk technique","performance evaluation of uml design with stochastic well-formed nets","a branch-and-price algorithm and new test problems for spectrum auctions"," performance of centralized bandwidth reservation protocol in unk","identical part production in cyclic robotic cells : concepts , overview and open questions","solution of a model describing biological species living together using the variational iteration method","digital unk : how does technology help new mothers ?","state machines as inductive types","design of robust business-to-business electronic marketplaces with guaranteed privacy","segmentation through variable-order surface fitting","experiments on semantic interoperability of agent reputation models using the unk architecture",
           "very large-scale neighborhood search for the quadratic assignment problem",
           "non-negative matrix factorization for semisupervised heterogeneous data coclustering",
           "energy-efficient power allocation in ofdm-based cognitive radio systems : a unk model",
           "reach control on simplices by continuous state feedback",
            "optimal balking strategies and pricing for the single server markovian queue with unk waiting space",
            "unk research is unk",
            "femtocell coverage optimization using switched multi-element antennas",
            "decentralized detection in sensor networks",
            "a study of supervised term weighting scheme for sentiment analysis",
            "transmit antenna selection based on outage probability for correlated mimo multiple access channels",
            "on the minimum size of binary codes with length 2r + 4 and covering radius r",
            "limit shape of a random integer partition with a bounded unk ratio of parts sizes",
            "status and outlook for dod configuration management requirements",
            "publisher 's message",
            "the use of group support systems in focus groups : information technology meets qualitative research",
                    "unk , software for well test analysis in fractured media combining fractional flow with double porosity and unk approaches",
                    "least-squares design of dft unk based on allpass transformation of higher order",
                    "unk formulas on the largest minimum distance of block codes",
                    "on the genus of a random graph",
                   " soft computing approach for modeling power plant with a unk boiler",
                   " analysis of e-learning innovation and core capability using a hypercube model",
                    "frequency analysis of noisy short-time stationary signals using unk",
                    "synchronized reneging in queueing systems with vacations",
                    "a generalized learning paradigm exploiting the structure of feedforward neural networks",
                   " distribution of lead in blood and organs of mice exposed to unk drinking water",
                   " rate-distortion efficient piecewise planar 3-d scene representation from 2-d images",
                    "target detection via network filtering",
                    "unambiguous state discrimination in quantum key distribution",
                    "machine learning for frequency estimation of power systems",
                    "let 's search together , but not too close unk an analysis of communication and performance in collaborative information seeking",
                    "a deterministic model selection scheme for incremental rbfnn construction in time series forecasting",
                    "most robust and fragile two-qubit entangled states under depolarizing channels",
                   " unk : a medical image retrieval system",
                    "the b-spline recurrence relations of unk and of unk",
                    "bit allocation for joint source and channel coding of progressively compressed 3-d models",
                   " ink display",
                    "a case for unk",
                    "or forum -- unk evolution of closed-loop supply chain research",
                   " b-spline backstepping control with derivative matrix estimation and its applications",
                   " optimization of unk turbo cdma systems",
                    "evolutionary optimization with markov random field prior",
                    "a reduced data set method for support vector regression",
                    "a fast local search method for minimum energy broadcast in wireless ad hoc networks",
                   " an algorithmic approach for analysis of unk retrial systems with unreliable servers",
                    "a new three-step search algorithm for block motion estimation",
                    "wireless transmission of ecg signal",
                    "frontal geometry from sketches of engineering objects : is line labelling necessary ?",
        "approximation algorithm for the weighted unk minimization on a single machine with a fixed unk interval",
        "optimization of wire electrical discharge machining for pure tungsten using a neural network integrated simulated annealing approach",
                "fusion of color edge detection and color quantization for color image watermarking using principal axes analysis",
        "on the unk order and properties",
                "equalization and space diversity techniques in mobile environments",
                "on the stability of distributed sequence adaptation for cellular asynchronous ds-cdma systems",
                "the iowa driving simulator : an immersive research environment",
        "improved quality function deployment method in employee turnover risk identification process",
        "testing for socs with advanced static and dynamic unk capabilities",
            "unk study of the relationship between number of gene splice variants and go categorization",
               "comparison of the nodal integral method and nonstandard finite-difference schemes for the fisher equation",
       "what determines an agreeable and unk idea ? a study of user ideas on unk",
       "experience with an evolving overlay network testbed",
        "on-the-fly data flow analysis based on verification technology",
                "principles of survey research part 4 : questionnaire evaluation",
        "total dual integrality of unk 's description of the unk polyhedron",
        "2010 special issue : neural network model for completing occluded contours",
       "construction of optimal subband coders using optimized and optimal quantizers",
                "on the coordinator 's rule for fast unk",
        "uncalibrated factorization using a variable symmetric affine camera",
               "analysis of digital random numbers generated from serial samples of correlated gaussian noise ( unk . )",
        "a quantitative version of unk 's approximation theorem",
       "efficient single-pass index construction for text databases",
            "identifying important concepts from medical documents",
                "supporting conceptual and neighborhood queries on the world unk",
        "a general stochastic clustering method for automatic cluster discovery",
       " on the convolution integral")



        val spinner = findViewById<Spinner>(R.id.spinner)
        if (spinner != null) {
            val arrayAdapter = ArrayAdapter(this, android.R.layout.simple_spinner_item, personNames)
            spinner.adapter = arrayAdapter

            spinner.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
                override fun onItemSelected(parent: AdapterView<*>, view: View, position: Int, id: Long) {
                    Toast.makeText(this@Recommendation, getString(R.string.selected_item) + " " + personNames[position], Toast.LENGTH_SHORT).show()
                }

                override fun onNothingSelected(parent: AdapterView<*>) {
                    // Code to perform some action when nothing is selected
                }
            }
        }
        val personName= arrayOf(
            "during the last few years , users unk over the world have become more and more accustomed to the availability this has boosted the use of a wide variety both of established and recent multimedia applications . however , there are cases where it is too expensive for network providers to serve a community of users . this is typically the case in rural and suburban areas , where there is slow deployment ( or no deployment in those cases , the most promising opportunity rests with broadband wireless access technologies , such as the ieee 802.16 one of the features of the mac layer of 802.16 is that it is designed to differentiate service among traffic this article focuses on mechanisms that are available in an 802.16 system to support quality of service ( qos )",
                    "the letter proposes a novel unk digital image watermarking scheme resisting the permutation attack . the unk watermarking schemes have drawn great attention for their convenience and effectiveness in recent years , but the traditional in this letter , the watermark information is embedded in the average values of the unk dwt coefficients to resist the concrete embedding process is achieved by the quantization-based method . experimental results show that the proposed scheme can resist not only the permutation attack but also some common image processing",
                    "based on frequency-domain unk techniques combined with an optimal model-order selection , this modeling method efficiently simulates microwave unk . a broadband microwave receiver ( with astronomical applications ) is modeled and simulated to illustrate the technique . this particular receiver is a challenging case because it samples cosmic microwave background ( unk ) low-power broadband ( unk)",
                    "motivation : a plugin for the java-based unk pathway editor has been developed to help users draw diagrams of unk together with the core unk application , this plugin presents a simple to use and cross-platform application for the construction this tool extends the capabilities of the unk pathway editor by providing both unk glyphs and support for a unk availability : the unk plugin is freely available and works with versions of unk unk and later on windows , information about mim notation and the unk format is available at http : unk . the plugin , along with diagram examples , instructions and java source code , may be downloaded at http : contact : unk @ unk ; unk @ unk supplementary information : supplementary data are available at bioinformatics online .",
        "two of the most used tools in the area of computer security are the firewalls and the intrusion detection systems both of them fulfill the task for which they were designed for but unfortunately their response to an attack can the communication of both tools increases the response capacity of the system , but we need a protocol to communicate in this paper we present how is to communicate two security tools : snort and unk . the communication is based on the intrusion detection message exchange format ( unk ) proposed by the intrusion detection working",
        "once students master the imperative programming paradigm , they find it hard to learn to work with a declarative language in order to help our students make the transition from imperative to pure declarative programming , we have identified many we have attempted to recast the semantics of commonly misunderstood data and control constructs in prolog in terms of the furthermore , in order to promote declarative rather than imperative programming in prolog , we have devised a set of we have found that these templates are helpful in teaching logic programming in our comparative programming languages unk this paper we will also present and analyze the templates we have developed to help our students make the transition from imperative finally , we will list some of the problems that our students have successfully solved over the years , as",
        "a graph is said to be uniquely list colorable , if it admits a list assignment which induces a unique we study uniquely list colorable graphs with a restriction on the number of colors used . in this way , we generalize a theorem which characterizes uniquely unk colorable graphs . we introduce the uniquely list chromatic number of a graph and make a conjecture about it which is a generalization",
        "as part of the effort to obtain accurate predictions of physical events , various parameter estimation techniques have been developed this study uses a bayesian estimation type error function . the newton-raphson optimization algorithm is used to find a simplified iterative algorithm that is used for finding a minimum extremum the study focuses largely on two items . first , in order to find a desired minimum of the error function , it is necessary to start the starting anywhere within this domain will result in finding the desired minimum . the unk unk of the convergence domain is usually very convoluted , thus making it more difficult to choose a a simple nonlinear example is studied to give a better picture of this problem .",
        "this article classifies all & unk ; Î´ ( q + 1 ) , Î´ & semi ; 3 , when q is a third power , the unk is the disjoint union of projected pg ( 5 ,sqrt this leads to a discrete spectrum for the small values of the deficiency Î´ of the corresponding maximal partial spreads",
        "we propose a novel method of video test bitstream for the h.264/avc decoder conformance test without using input image sequences although the bitstreams can be generated from encoding the natural or artificial image sequences by a reference video encoder , the proposed method employs the unk techniques to produce highly randomized video parameters in its bitstream . according to the experimental results , it substantially improves the function coverage and reduces the test time compared to those moreover , we can also generate the arbitrary bitstreams for stress test with the extreme values in the allowable ranges",
        "the scope of this study is to diagnose vertebral arterial inefficiency by using doppler measurements from both right and left total of 96 patients ' doppler measurements , consisting of 42 of healthy , 30 of unk , and 24 patients ' age and sex information as well as unk , unk , unk , unk , and unk medical the area under roc curve , which is a direct indication of repeating success ratio , is calculated as unk it is also demonstrated that those medical parameters of age and systolic velocity , which were applied into the neural",
        "today 's networked computer systems are very vulnerable to attack : terminal software , like that used by the x many other software products , including operating systems , load parts of themselves from a server across a network . although users may be confident that their workstation is physically secure , some part of the network to which they most proposals that recommend cryptographic means to protect remotely loaded software also eliminate the advantages of remote loading -- for for this reason , they have largely been abandoned before finding their way into commercial products . this article shows that , contrary to intuition , it is no more difficult to protect a workstation that loads in contrast to prevailing practice , the authors make essential use of a unk hash function to ensure that an this strategy forces the opponent into an open , on-line guessing attack and offers the user a defensive strategy unavailable",
        "the concept of instantaneous parameters , which has previously been associated exclusively with 1-d measures like the instantaneous frequency and such generalized instantaneous parameters are associated with the short-time fourier transform . they may also be interpreted as local moments of certain time-frequency distributions . it is shown that these measures enable local signal behavior to be characterized in the time-frequency plane for nonstationary deterministic the usefulness of the generalized instantaneous parameters is demonstrated in their application to optimal selection of windows for spectrograms . this is achieved through window matching in the time-frequency plane . an algorithm is provided that illustrates the performance of this window matching . results based on simulated and real data are presented",
        "by means of the unk formula , we establish two new matrix inversions with four parameters . these new inversions unk riordan 's inverse relations of unk , unk , and unk as well as unk 's some related q-series inverse relations using the known unk of the unk formula are established . a @ unk of unk 's unk , a novel expression for all unk inversions , and several new summation",
        "this paper presents a new methodology to simulate soft object deformation by drawing an analogy between a cellular neural network the potential energy stored in an elastic body as a result of a deformation caused by an external force is the novelty of the methodology is that : 1 ) cnn techniques are established to describe the potential energy distribution integration with a haptic device has been achieved for deformable object simulation with force feedback . the proposed methodology not only predicts the typical behaviors of living tissues , but it also accommodates isotropic , anisotropic",
        "profile data is valuable for identifying program hotspots and guiding optimizations . traditional software profiling techniques incur significant overhead and are not suitable for unk ( dynamic binary translation ) systems . hardware can support profile collection through either counters or timer interrupts that permit collection of statistical samples via software . most unk profiling systems can only achieve either high profile accuracy or low overhead . in this paper , we propose a novel profile approach on unk using hardware support technique to achieve rapidly and this approach makes use of instrumentation code and a set of profiling hardware which supports operations of updating counters . it is believed that such a software-hardware collaborative approach will serve to provide a strong foundation for optimizing unk systems",
        "the paper presents a method to compute performance metrics ( response time , sojourn time , throughput ) on unified the method starts with uml design annotated according to the uml profile for schedulability , performance and time . the uml design is transformed into a performance model where to compute the referred metrics . being the performance model a stochastic well-formed net , the method is enabled to analyze systems where the object identities a complete case study reveals how to apply the method and its usefulness .",
        "when combinatorial bidding is permitted in auctions , such as the proposed fcc auction # 31 , the resulting full we present a branch-and-price algorithm based on a unk formulation originally proposed by unk and forrest ( 2002 , unk the ima volumes in mathematics and its applications , vol . 127 , unk , new york , unk ) . this formulation has a variable for every possible combination of winning bids for each bidder . our algorithm exploits the structure of the unk bidding language used by the fcc . we also present a new methodology to produce realistic test problems based on the unk results of fcc auction # we generate unk test problems , which involve 99 items and are substantially larger than most of the previously used",
        "atm based virtual private networks ( unk ) are embedded in public atm network to provide an efficient transport service in this paper we propose a centralized protocol for resource allocation in unk and compare its performance with that of we analyze the protocol to get average burst delay and burst loss probability in case of finite buffering at the",
        "robotic cells consist of a flow-shop with a robot for material handling . a single part is to be produced cyclically and the objective is to minimize production rate . this document introduces basic concepts and tools for dealing with cyclic production . in particular , it concentrates on unk which are production cycles where exactly k parts enter and leave the cell one defines the cycle function k which is the smallest value of k so that the set of all unk known results and conjectures on these functions are given for the classical case where parts can remain on the machine",
        "in this work , a system of two nonlinear integro-differential equations which arises in biology is considered and the well-known this method is based on the incorporation of a general lagrange multiplier in the construction of correction functional for the this technique reduces the volume of calculations by not requiring discretization of the variables , linearization or small perturbations and also a numerical technique based on the pseudospectral legendre method is developed to solve the model . several test problems are given and the results are compared with adomian decomposition method and the variational iteration technique .",
        "new mothers can experience social exclusion , particularly during the early weeks when infants are solely dependent on their mothers we used ethnographic methods to investigate whether technology plays a role in supporting new mothers . our research identified two core themes : ( 1 ) the need to improve confidence as a mother ; and we reflect on these findings both in terms of those interested in designing applications and services for unk and also",
        "we describe a way to write state machines inductively . the proposed method makes it possible to use the standard techniques for proving theorems on inductive types to verify that a mutual exclusion protocol using a queue is used to exemplify the proposed method .",
        "firms that set up electronic marketplaces to enhance their supply and/or distribution channels face challenges in attracting their competitors to a major obstacle is the perception that the owner can unk exploit trading information for competitive advantage . in this paper , we propose a marketplace design that shifts the locus of control over trader privacy from the we show how online transactions between trading partners can be conducted in total privacy , so that not even the at the same time , our approach includes robust methods for transaction integrity and unk , as well as unk",
        "the solution of the segmentation problem requires a mechanism for partitioning the image array into low-level entities based on a a piecewise-smooth surface model for image data that possesses surface coherence properties is used to develop an algorithm that simultaneously surface curvature sign labeling provides an initial coarse image segmentation , which is refined by an iterative region-growing method based experimental results show the algorithm 's performance on six range images and three intensity images .",
        "in the last decades , we have experienced a rapid increase in the number of available online e-services . agent-based computing has been advocated as a natural computational model to automate the interaction with those services , thus enabling in these latter , agents may use trust and reputation as the main control mechanism and they usually exchange such however , due to the semantic heterogeneity of the different reputation models , agents interaction about reputation has to deal therefore , this paper presents some experiments using unk , an architecture that enables the semantic interoperability among agents that such experiments were conducted using two reputation testbeds and three agent reputation models in order to analyze the accuracy of",
        "the quadratic assignment problem ( qap ) consists of assigning n facilities to n locations to minimize the total weighted the qap arises in many diverse settings , is known to be np-hard , and can be solved to optimality neighborhood search algorithms are the most popular heuristic algorithms for solving larger instances of the qap . the most extensively applied neighborhood structure for the qap is the unk neighborhood . this neighborhood is obtained by swapping the locations of two facilities ; its size is therefore o ( n2 ) previous efforts to explore larger neighborhoods ( such as unk or unk neighborhoods ) were not very successful , as in this paper , we propose very large-scale neighborhood ( unk ) search algorithms when the size of the neighborhood our search procedure relies on the concept of an improvement graph that allows us to evaluate neighbors much faster than",
        "coclustering heterogeneous data has attracted extensive attention recently due to its high impact on various important applications , such us however , data coclustering without any prior knowledge or background information is still a challenging problem . in this paper , we propose a semisupervised non-negative matrix factorization ( unk ) framework for data coclustering . specifically , our method computes new relational matrices by incorporating user provided constraints through simultaneous distance metric learning and modality using an iterative algorithm , we then perform unk of the new matrices to infer the clusters of different data theoretically , we prove the convergence and correctness of unk coclustering and show the relationship between unk with other well-known through extensive experiments conducted on publicly available text , gene expression , and image data sets , we demonstrate the",
        "efficient and reliable subcarrier power allocation in orthogonal frequency-division multiplexing ( ofdm ) -based cognitive radio networks is a challenging traditional waterfilling approach is inefficient for such networks due to the strict requirements on the interference generated to the primary in this paper , we present a solution to an energy-efficient resource allocation problem which maximizes the cognitive radio ( we consider an energy-aware capacity expression by taking into account another factor called subcarrier availability . optimizing such an expression saves valuable resources such as battery life by selectively allocating power to underutilized subcarriers . based on a unk model , we formulate a convex optimization problem which incorporates a linear average rate loss function due to the complex structure of the optimal solution , we propose three suboptimal schemes , namely , the unk we compare the performances of optimal and suboptimal algorithms with the performance of a classical waterfilling scheme .",
        "this paper studies a theoretical problem of whether continuous state feedback and affine feedback are equivalent from the point of we show that the two classes of feedbacks are equivalent . as a byproduct , new necessary and sufficient conditions for solvability based more directly on the problem data are obtained",
        "this paper explores focus groups supported by group support systems ( gss ) with anonymous interaction capability in two configurations after reviewing the literature , we compare and contrast these unk unk focus groups with traditional focus groups and discuss we suggest directions for future research concerning unk focus groups with respect to technological implications ( typing skills and connection deception and design : the impact of communication technology on lying behavior . proceedings of the 2004 conference on human factors in computing systems ( pp . unk ) , whereby lying is a function of three design factors : synchronicity , unk , and unk )",
        "we consider the single server markovian queue and we assume that arriving customers decide whether to enter the system or before making his decision , a customer may or may not know the compartment in which he will enter and/or thus , denoting by n the number of customers found by an arriving customer , he may or may not we also study the corresponding social and profit maximization problems .",
        "according to the 16 august 2005 wall street journal , federal unk are increasingly forcing universities to pay back unk interestingly , the paper cites a study by unk research foundation and the university of minnesota that found more than apparently , to get a research grant , you already have to have done the work .",
        "femtocells are low-cost , low-power cellular base stations that are deployed by the end user to supplement unk coverage and in femtocell deployments , leakage of the pilot signal to the outside of a house can result in a highly in this paper , a low cost multi-element antenna solution is proposed to reduce the core network mobility signalling over antenna gain pattern measurements of a prototype with two patches and two inverted f antennas are presented and a corresponding self-optimization methods are proposed that jointly select an appropriate antenna pattern and optimize the pilot power . this allows to better match the femtocell coverage to the shape of each individual house and results in an improvement",
        "in this paper , we investigate a binary decentralized detection problem in which a network of wireless sensors provides relevant each sensor transmits its data over a multiple access channel . upon reception of the information , the fusion center attempts to accurately reconstruct the state of nature . we consider the scenario where the sensor network is constrained by the capacity of the wireless channel over which the for the problem of detecting deterministic signals in additive gaussian noise , we show that having a set of identical thus , the gain offered by having more sensors exceeds the benefits of getting detailed information from each sensor . a thorough analysis of the gaussian case is presented along with some extensions to other observation distributions .",
        "term weighting is a strategy that assigns weights to terms to improve the performance of sentiment analysis and other text in this paper , we propose a supervised term weighting scheme based on two basic factors : importance of a for itd , we explore three definitions based on term frequency . then , seven statistical functions are employed to learn the its of each term from training documents with category labels compared with the previous unsupervised term weighting schemes originated from information retrieval , our scheme can make full use of we have experimentally evaluated the proposed method against the state-of-the-art method . the experimental results show that our method outperforms the method and produce the best accuracy on two of three data",
        "two new algorithms are presented to select the number and subset of active transmit antennas among the users in a the algorithms are based on the outage probability of a multiuser spatial multiplexing system using independent decoding with linear and a key advantage of these algorithms is the avoidance of tracking the fading channel by using channel covariance matrices rather the first algorithm selects the active transmit antennas to minimize the total transmit power among the users given the outage the second algorithm selects the active transmit antennas to maximize the sum rate of the multiple access channel given the in comparison to a system using all available transmit antennas , both selection algorithms provide significant performance gains in correlated in addition , the algorithms exhibit gains for linear receivers in independent fading",
        "the minimum size of a binary code with length n and covering radius r is denoted by k ( n for arbitrary r , the value of k ( n , r ) is known when n é©´ 2r + by combining combinatorial and computational methods , several results for the first open case , k ( 2r + 4 )" ,
        "we consider an integer partition @ l unk 1= ... = @ l unk @ ? , @ ? unk does not exceed a given number k1 . for k=2 , unk unk had conjectured existence of a constant a such that the random function m unk unk unk x unk m unk unk unk n unk @ ? , x @ ? [ unk ] ( m unk unk ) , converges in probability to unk ( x ) unk , f we confirm a natural extension of unk 's conjecture for k1 , and show that the limit shape unk ( in particular , for k=2 , w is the golden ratio ( unk ) unk .",
        "since the release of department of defense ( dod ) directive unk , unk of computer resources in major defense a review of the current status of configuration management within the dod computer resources management environment is provided , and",
        "first page of the article",
        "the identification of the hydraulic characteristics and transport properties of fractured reservoirs requires the development of specific models that account the presence of major conductive fractures that delimit capacitive matrix blocks , with weakly open , dead end or isolated well tests in fractured media ( unk ) software takes into account these two main features by combining radial flow the implementation of this nd model , with n fractional , extends usefully the domain of application of the usual although the fractures geometry and properties are not considered one by one , or by directional families , they are the accuracy of the coupled transient behaviours analysis is augmented by taking into account wellbore storage and skin effects . all together , the use of these different options allows matching a wide range of pumping test curves , characteristics distinctive well test experiments , in both sedimentary and crystalline rocks , are presented for unk how the pertinent use",
        "the allpass transformation of higher order is a very general concept to construct a frequency warped analysis-synthesis filter bank ( in contrast to the more common allpass transformation of first order , the delay elements of the analysis filter bank known analytical closed-form designs for the synthesis filter bank can ensure perfect reconstruction ( pr ) , but the synthesis these problems are addressed by a new least-squares error ( lse ) filter bank design . the coefficients of the finite-impulse-response ( fir ) synthesis filters are determined simply by a linear set of equations where this approach can achieve a perfect signal reconstruction with synthesis filters which are inherently stable and feature a bandpass characteristic the proposed filter bank is of interest for various subband processing systems requiring nonuniform frequency bands .",
        "a general formula for the asymptotic largest minimum distance ( in block length ) of deterministic block codes under generalized as revealed in the formula , the largest minimum distance can be fully determined by the ultimate statistical characteristics of interestingly , the new formula has an analogous form to the general unk expressions of the channel capacity and the as a result , a minor class of distance functions for which the largest minimum distance can be derived is a general unk lower bound is next addressed . some discussions on the tightness of the general unk bound are also provided . finally , lower bounds on the largest minimum distances for several specific block coding schemes are unk in terms of",
        "let p = p ( n ) be a function of n with unk , p ) ; that is unk and unk have shown that if p2 ( 1 âˆ’ p2 ) & # unk ; 8 ( log then the ( orientable ) genus of a random graph in & # unk ; ( n , p ) we prove that for every integer i unk 1 , if unk ( i + 1 ) unk p unk then the genus of a random graph in & # unk ; ( n , p ) is ( 1 if p = unk ( unk ) unk , where c is a constant , then the genus of a Â© 1995 wiley unk , inc .",
        "in this paper , a soft computing approach is presented for modeling electrical power generating plants in order to characterize the structure of the soft computing method consists of fuzzy logic , neural networks and genetic algorithms . the measured data from a complete set of field experiments is the basis for training the models including the extraction the genetic algorithm is applied to the modeling approach in order to optimize the procedure of the training . comparison between the responses of the proposed models with the responses of the plants validates the accuracy and performance of a similar comparison between the responses of these models with the models obtained based on the thermodynamical and physical relations",
        "new information and communication technologies and emerging learning models have triggered a new wave of educational unk learning ( e-learning this study utilizes a hypercube innovation model to analyze the differences in technology and learning models ( instruction unk ) the results show that the innovation from traditional classroom learning to e-learning is radical for both the learner and instructor for educational institutions , the technology is a fundamental change , while the learning model is reinforced . from the dynamic capability perspectives , a set of core capabilities needed for successfully exploiting e-learning is identified . these results provide insight for learners , instructors and educational institutions for enhancing their understanding of e-learning innovation , and",
        "spectral reconstruction of short signals is a problem relevant to many areas of engineering and science . classical techniques , unk . fourier transform ( ft ) and the wavelet transform ( wt ) fail to provide accurate estimates of the low to cope with the problem this paper brings up the method of unk ( fd ) , developed in the a natural question occurs as to whether it is robust to noise unk the signal and thus applicable to signal in this paper the fd method is first unk from the point of view of linear state-space systems dynamics . it is shown that the original fd modifies to an essentially stochastic generalized eigenvalue problem with underlying matrices being normally the results of a monte carlo simulation study are summarized showing that the fd method displays monotonous behaviour with respect",
        "in this paper we present a detailed analysis of queueing models with vacations and impatient customers , where the source instead of the standard assumption that customers perform independent unk , we consider situations where customers abandon the system simultaneously this is , for example , the case in remote systems where customers may decide to abandon the system",
        "in this paper a general class of fast learning algorithms for feedforward neural networks is introduced and described . the approach exploits the separability of each layer into linear and nonlinear blocks and consists of two steps . the first step is the descent of the error functional in the space of the outputs of the linear blocks in the second step , each linear block is optimized separately by using a least squares ( ls ) criterion to demonstrate the effectiveness of the new approach , a detailed treatment of a gradient descent in the neuron space the main properties of this approach are the higher speed of convergence with respect to methods that employ an ordinary the numerical stability is assured by the use of robust ls linear system solvers , operating directly on the input experimental results obtained in three problems are described , which confirm the effectiveness of the new method",
        "pb levels in blood , liver , lung , kidney , heart and brain of male mice were measured after the resultant data show that 98 % of lead exposed in blood is accumulated in red blood cells . for other target organs , the accumulation of lead is in an order of kidney , liver , unk , the accumulation of lead in brain gradually increases with lead exposure while the accumulation of lead in the other target",
        "in any practical application of the unk conversion that involves storage and transmission , representation efficiency has an unk importance in order to address this problem , a novel algorithm , which yields efficient 3-d representations in the rate distortion the algorithm utilizes two views of a scene to build a mesh-based representation incrementally , via adding new vertices , the experimental results indicate that , in scenes that can be approximated by planes , the proposed algorithm is superior",
        "a method of network filtering has been proposed recently to detect the effects of certain external perturbations on the interacting however , with large networks , the goal of detection seems a priori difficult to achieve , especially since the under the assumption that the network possesses a certain sparsity property , we provide a formal characterization of the accuracy we explore the implications of the technical conditions underlying our characterization , in the context of various network topologies" ,
        "the quantum circuit and design are presented for an optimized entangling probe attacking the bb84 protocol of quantum key distribution probe photon polarization states become optimally entangled with the signal states on their way between the legitimate transmitter and receiver although standard unk projective measurements of the probe yield maximum information on the unk amplified key , if instead the it follows that the bb84 ( unk -- unk 1984 ) protocol of quantum key distribution has a vulnerability similar" ,
        "in this paper the application of machine learning techniques for on-line dynamic security assessment of power systems is presented . decision trees ( dt ) , artificial neural networks ( ann ) and entropy networks ( en ) are developed comparison of these methods reveals their relative advantages and disadvantages . these methods have been integrated in the dynamic security assessment module of the advanced control system of unk island , the results are considered very satisfactory , both in accuracy that increases the reliability of the method and in computational",
        "communication is considered to be one of the most essential components of collaboration , but our understanding as to which to help investigate effects of various communication channels on a collaborative project , we conducted a user study with 30 using both quantitative and qualitative data analysis , we found that teams with remotely located participants were more effective in adding audio support for remote collaboration helped participants to lower their cognitive load as well as negative emotions compared to we also show how these findings could help design more effective systems for collaborative information seeking tasks using adequate and we argue that collaboration is an important aspect of human-centered ir , and that our work provides interesting insights into",
        "this paper presents a fast and new deterministic model selection methodology for incremental radial basis function neural network ( rbfnn the development of such special designed methodology is motivated by the problems that arise when using a k-fold unk model taking into account these drawbacks , the proposed model selection approach is a combined algorithm that takes advantage of two this way , the model prediction accuracy is improved , getting small variance and bias , reducing the computation time",
        "for a two-qubit system under local depolarizing channels , the most robust and most fragile states are derived for a for the one-sided channel , the pure states are proved to be the most robust ones , with the aid [ nat . phys . 4 , 99 ( 2008 ) ] . based on a generalization of the evolution equation for entanglement , we classify the ansatz states in our investigation by for the two-sided channel , the pure states are the most robust for a fixed concurrence . under the uniform channel , the most fragile states have the minimal negativity when the concurrence is given in the",
        "the next generation of medical information system will integrate multimedia data to assist physicians in clinical decision-making , diagnoses , this paper describes unk ( medical image annotation and retrieval system ) . unk not only provides automatic annotation , but also supports text based as well as image based retrieval strategies , the system utilizes three trained classifiers , which are trained using training images . the goal of these classifiers is to provide multi-level automatic annotation . another main purpose of the unk system is to study image semantic retrieval strategy by which images can be retrieved",
        "we discuss the early history of b-splines with an arbitrary knot sequence , and of their recurrence relations . these seem to have first appeared in papers of unk and unk from the unk .",
        "this work presents a joint source and channel coding method for transmission of progressively compressed three-dimensional ( 3-d ) models the proposed system uses the compressed progressive mesh ( cpm ) algorithm to produce a hierarchical bitstream representing different levels in addition to optimizing the transmitted bitstream with respect to the channel characteristics , we also choose the optimum combination that is , given a 3-d mesh , a total bit budget ( b ) and a channel packet-loss rate experimental results show that , with our unequal error protection approach that uses the proposed bit-allocation algorithm , the decoded",
        "first page of the article",
        "a new control structure construct , the unk , is introduced as a syntactic combination of the while and the examples are shown indicating that use of the unk can lead to structured programs that are conceptually more manageable than the unk statement is then extended to a unk expression which is shown to be more powerful than either the",
        "the purpose of this paper is to introduce the reader to the field of closed-loop supply chains with a strong it recounts the evolution of research in this growing area over the past 15 years , during which it developed we use five phases to paint an encompassing view of this evolutionary process for the reader to understand past achievements",
        "a b-spline backstepping controller is proposed for a class of multiple-input multiple-output ( mimo ) nonlinear systems . the control scheme incorporates the backstepping design technique with a b-spline neural network which is utilized to estimate the system the b-spline neural network has the advantage of locally controlling its output behavior compared with other neural networks ; therefore based on the mean-value theorem , the derivative of b-spline basis functions in relation to parameters can be estimated to in addition , the validity of the proposed scheme is verified through an experiment on a servo motor system which",
        "we consider the analysis and design of low-density parity-check ( ldpc ) codes for turbo multiuser detection in multipath code we develop techniques for computing the probability density function ( pdf ) of the extrinsic messages at the output of of particular interest is the soft interference cancellation plus minimum mean square error ( unk ) multiuser detector , for for the case of additive white gaussian noise ( awgn ) channels , the extrinsic messages can be well approximated for the case of asynchronous multipath fading channels , the extrinsic messages can be approximated by a mixture of symmetric we show that the expectation-maximization ( em ) algorithm can be used to compute the parameters of this mixture . using these techniques , we are able to accurately compute the thresholds for ldpc codes and design good irregular ldpc simulation results are in good agreement with the computed thresholds , and the designed irregular ldpc codes outperform regular ones",
        "this work discusses an evolutionary algorithm in which the constituent variables of a solution are modeled by a markov random we maintain a population of potential solutions at every generation and for each solution a fitness value is calculated . the evolution , however , is not achieved through genetic recombination . instead , each variable in a solution will be updated by sampling from its probability distribution . according to the mrf prior , local exploitation is encoded in the conditional probabilities . for evolutionary exploration , we estimate the probabilities as unk statistics . these two kinds of search are combined smoothly in our algorithm . we compare it with two representative algorithms [ iterated conditional modes ( icm ) and simulated annealing ( sa )",
        "support vector regression ( svr ) has been very successful in pattern recognition , text categorization , and function approximation the theory of svr is based on the idea of structural risk minimization . in real application systems , data domain often suffers from noise and outliers . when there is noise and/or outliers exist in sampling data , the svr may try to fit those improper data in addition , the memory space for storing the kernel matrix of svr will be increment with o ( n^2 hence , for a large training data set , the kernel matrix can not be saved in the memory . in this paper , a reduced support vector regression is proposed for nonlinear function approximation problems with noise and outliers the core idea of this approach is to adopt fuzzy clustering and a robust fuzzy c-means ( unk ) algorithm",
        "local search methods are often used to reduce the power consumption of broadcast routing in wireless networks . for a classic method , sweep , the best available time complexity result is o ( unk ) . we present an o ( unk ) unk method , which exhaustively removes unnecessary transmissions yielding a solution comparable to",
        "this paper aims at presenting an approach for analyzing unk retrial systems with servers subject to breakdowns and repairs , this high-level formalism allows a simple representation of such systems with different breakdown disciplines . from the unk model , a continuous time markov chain ( ctmc ) can be automatically derived . however , for multiserver retrial systems with unreliable servers , the models may have a huge state space . using the unk model as a support , we propose an algorithm for directly computing the infinitesimal generator of the in addition , we develop the formulas of the main stationary performance and reliability indices , as a function of through numerical examples , we discuss the effect of the system parameters and the breakdown disciplines on performance .",
        "the three-step search ( tss ) algorithm has been widely used as the motion estimation technique in some low bit-rate however , tss uses a uniformly allocated checking point pattern in its first step , which becomes inefficient for the a new three-step search ( unk ) algorithm is proposed in the paper . the features of unk are that it employs a unk checking point pattern in the first step , which is simulation results show that , as compared to tss , unk is much more robust , produces smaller motion compensation",
        "in this study , the ecg signal were measured as noiseless with unk electrodes , then converted digital data using the digital data were then sent to receiver where it is in unk mhz unk transmitter , which has 10 at the receiver , the digital data were unk to analog signal to monitor and record on the pc with the power spectrum of measured ecg signal was formed using matlab program . as a result , the medical supporting system is realized for monitoring the ecg signal on pc of human with",
        "a tool which can quickly interpret line drawings ( with hidden lines removed ) of engineering objects as boundary representation inflation of the drawing to produce a frontal geometry , a geometric realisation of that part of the object visible previous methods of producing frontal geometries have relied on the technique of line labelling ( labelling edges as convex , although restricted subsets of the unk problem have known solutions , reliable methods have not been found for the general many other papers assume that line labelling is an essential step . here , we show this is not necessarily true , and that comparable results can be obtained by a novel firstly , we consider what outputs from line labelling are essential to the production of frontal geometry . secondly , we investigate by what other means these outputs can be produced .",
        "in this article , we consider the unk case of the single machine scheduling problem with a fixed unk interval we aim to minimize the weighted sum of completion times . no polynomial 2-approximation algorithm for this problem has been previously known . we propose a 2-approximation algorithm with o ( n^2 ) time complexity where n is the number of jobs . we show that this bound is tight . the obtained result outperforms all the previous polynomial approximation algorithms for this problem .",
        "this study analyzed variation of cutting velocity and workpiece surface finish depending on wire electrical discharge machining ( unk ) a method integrating back-propagation neural network ( bpnn ) and simulated annealing algorithm ( saa ) is proposed to determine the specimens are prepared under different unk process conditions based on a taguchi orthogonal array table . the results of 18 experimental runs were utilized to train the bpnn predicting the cutting velocity , roughness average ( in addition , the analysis of variance ( anova ) was implemented to identify significant factors for the unk process the results of proposed algorithm and confirmation experiments are show that the unk method is effective tool for the optimization",
        "in the past few years , many gray-level image watermarking schemes have been proposed , although the extension to the this paper presents a new color image watermarking scheme that combines color edge detection and color quantization using principal axes the watermark is hidden within the data by modifying a subset of carefully selected edge points to resist both geometric experimental results show the robustness of the proposed scheme to resist common attacks .",
        "for a t-norm t on [ unk ] , a partial order @ ? unk t was recently defined and studied . in this study , for any fixed c @ ? ( unk ) , we define the set of incomparable elements according to @ ? unk t and this set is deeply investigated . by means of the equivalence relation , defined in [ 14 ] , it is shown the set [ unk finally , with the help of any t-norm t on [ unk ] , it is obtained that the family unk ( unk 0 unk , unk 1 unk ) of t-norms on [ unk ] .",
        "the development of high-quality digital mobile radio systems has become a major goal in the field of digital communications . the possibility of providing speech and data services free of wire unk in different environments is a very attractive proposition the aim of the present article is to analyze the behavior of different receiver structures for such systems in order these systems have to provide both low- and high-data-rate services ( up to 1 mb/s ) and be efficient in moreover , as the carrier frequencies will range between 1 and 4 ghz , and the vehicle speed can be under certain conditions , diversity techniques perform better than equalization techniques in typical mobile radio environments",
        "we consider the sequence adaptation problem for cellular asynchronous code-division multiple-access ( cdma ) systems . a game-theoretic approach is used to investigate the stability issues of distributed adaptation algorithms . it is shown that the nash equilibrium may not exist for cellular cdma systems if the traditional interference measure is in turn we propose a new interference measure which ensures system stability .",
        "the iowa driving simulator ( ids ) is a high-fidelity , immersive virtual environment for driving simulation . it supports a variety of applications , ranging from traffic safety research to full-scale test and evaluation of vehicle designs the ids places an operator at the controls of a detailed , computational vehicle model in a rich , fully the immersive virtual environment can create a range of driving conditions from high density , unk urban unk to unk a wide variety of scenarios and events can be specified to meet experimental needs . the authors describe the capabilities and underlying architecture of the ids and the approach used to model and control the several current applications of the ids are highlighted , including its use in the study of unk issues for an as of july 1995 , approximately 1,000 experimental runs have been conducted in conjunction with 22 separate studies using the",
        "employee turnover risk identification is a process to find the risk factors of employee turnover exactly , and it 's quality function deployment method is a unk unk unk quality engineering method aims at increasing the customer satisfaction level . after analyzing the employee turnover risk factors that would threaten enterprise production and operation activities , we propose a multi-level the application of improved quality function deployment method in employee turnover risk identification mainly involves configuring the employee turnover risk it proves well to use the improved quality function deployment method in employee turnover risk identification process .",
        "many multicore chips today employ advanced power management techniques . multi-threshold cmos ( mtcmos ) is very effective for reducing standby leakage power . dynamic voltage scaling and voltage islands which operate at multiple power-supply voltage levels , minimize dynamic power consumption . effective defect screening for such chips requires advanced test techniques that target defects in the embedded cores and the power we describe recent advances in test generation and test scheduling techniques for socs that support power switches , voltage islands",
        "motivation : splice variation plays important roles in evolution and cancer . different splice variants of a gene may be characteristic of particular cellular processes , subcellular locations or organs . although several genomic projects have identified splice variants , there have been no large-scale computational studies of the relationship between the gene ontology ( go ) and tools for leveraging go , such as unk , now make such a results : we partitioned genes into two groups : those with numbers of splice variants unk and b ( unk then we used unk to determine whether any go categories are enriched in genes with particular numbers of splice variants since there was no a priori unk appropriate unk partition boundary , we studied those unk robust unk categories whose furthermore , because the distribution of splice variant number was a snapshot taken at a particular point in time ,",
        "the relationship between the so-called nonstandard finite-difference schemes and the nodal integral method ( nim ) is investigated using the exact and best finite-difference schemes are reviewed first . next , the nim for the fisher equation is developed . it is shown that the nim leads to a nonstandard evaluation of the derivatives . moreover , the resulting scheme possesses the desirable characteristics of the nonstandard finite difference schemes , such as the nonlocal thus , the nim provides a systematic framework to obtain schemes similar to the best finite-difference schemes . numerical results for a propagating front problem show that the nim can capture the shape and speed of the front results also show that the best finite-difference scheme is stable for large grid sizes but only at the cost of",
        "rising tide of crowd sourcing as a new method of innovation is unk across diverse industries . considering that the goal of crowd sourcing is generating ideas which can be seeds of innovation , understanding the characteristics in our approach , we extract idea contents characteristics such as subjectivity , negativity , public unk , and depth an analysis of unk ideas from my star unk unk shows that there are significant differences between unk and unk besides , moderating effect of user reputation is found . managerial implications are discussed .",
        "the mit ron testbed consists of 36 unk nodes at 31 different unk . it has been in operation for two years . this paper presents an overview of the testbed , summarizes some of the research for which it has proved useful the testbed has been useful both for our own research and for that of external researchers unk of its heterogeneous",
        "the combination of static and dynamic software analysis , such as data flow analysis ( dfa ) and model checking on the one hand , the information extracted by dfas about program data may be utilized by model checkers to on the other hand , the expressiveness of logic formulas allows us to consider model checkers as generic data flow following this second approach , we propose in this paper an algorithm to calculate dfas using on-the-fly resolution of boolean the overall framework includes the abstraction of the input program into an implicit labeled transition system ( lts ) , moreover , using unk as an intermediate representation allowed us to reformulate classical dfas encountered in the literature , which our work was implemented and integrated into the widespread verification platform unk , and experimented on real examples .",
        "this article discusses how to avoid biased questions in survey instruments , how to motivate people to complete instruments and in the context of survey evaluation , we discuss how to assess survey reliability unk . how reproducible a survey 's data is and survey validity unk . how well a survey instrument measures what it sets out to measure .",
        "unk showed that the convex hull of the stable matchings of a bipartite preference system can be described by an in this paper we prove that the description given by unk is totally dual integral . we give a constructive proof based on the results of unk and unk on rotations , which gives rise to",
        "when some parts of a pattern are occluded by other objects , the visual system can often estimate the shape this paper proposes a neural network model capable of such function , which is called unk completion . the model is a hierarchical multi-layered network that has bottom-up and top-down signal paths . it contains cells of area v1 , which respond selectively to edges of a particular orientation , and cells of using the responses of unk cells , the model predicts the curvature and location of the occluded contours . missing contours are gradually extrapolated and interpolated from the visible contours . computer simulation demonstrates that the model performs unk completion to various stimuli in a similar way as observed by psychological",
        "a method is presented for the optimization of arbitrary quantizers by use of a compensating postfilter . it is shown that the resulting optimized quantizers fit the model of a linear time-invariant filter followed by additive noise on the basis of this model , an expression for the variance of the error of a subband coder using given analysis filters which statistically separate the subbands , it is shown that this variance is minimized if these synthesis the globally optimum filter bank , minimizing the coder error variance , is further obtained by proper choice of its a novel method for the determination of optimal bit allocation to subbands of the filter banks with optimized quantizers is the results are evaluated experimentally by comparison of the optimum uniformly split subband image coding scheme to classical unk filter",
        "fast unk is an algorithm for consensus that works by a succession of rounds , where each round tries to rounds are started by a coordinator process and consistency is guaranteed by the rule used by this process for the we show a simplified version of this rule for the specific case where the quorums are defined by the cardinality this rule is of special interest for unk of the algorithm .",
        "in order to reconstruct 3-d euclidean shape by the unk factorization , one needs to specify an affine camera model we present a new method that does not require any such specific models . we show that a minimal requirement for an affine camera to mimic perspective projection leads to a unique camera model we determine their values from input images by linear computation and demonstrate by experiments that an appropriate camera model is",
        "an analysis of digital random numbers generated from serial samples of gaussian noise is presented . a methodology is developed for calculating the word probability distribution in terms of the autocorrelation function of the noise . examples are presented for three and four bit words . a related problem is also considered which concerns the noise unk function . bounds are derived which take into account nonideal effects of the filter used to shape the noise spectrum . an example is given for a modified unk bandpass model .",
        "a quantitative version , based on modified unk , of the classical unk 's theorem concerning the approximation of c the result is applied to the study of the degree of convergence of the iterated bernstein operators on the n-dimensional",
        "efficient construction of inverted indexes is essential to provision of search over large collections of text data . in this article , we review the principal approaches to inversion , analyze their theoretical cost , and present experimental we identify the drawbacks of existing inversion approaches and propose a single-pass inversion method that , in contrast to previous we show that the performance of the single-pass approach can be improved by constructing inverted files in segments , reducing",
        "automated medical concept recognition is important for medical informatics such as medical document retrieval and text mining research . in this paper , we present a software tool called unk identification program ( unk ) for identifying topical concepts unk combines two functions : noun phrase extraction and unk identification . the former automatically extracts noun phrases from medical literature as unk candidates . the latter assigns weights to extracted noun phrases for a medical document based on how important they are to that the experimental results show that our noun phrase extractor is effective in identifying noun phrases from medical documents , so they both performed better than the systems they were compared to .",
        "a document retrieval system mainly consists of three components : document representation , user queries , and document evaluation . each component may involve some uncertainties . fuzzy set theory is a natural approach to coping with the representation of documents , queries , and the relevance the authors propose a fuzzy document retrieval model on the world wide web ( www ) environment to support conceptual a flexible query expression is proposed to support different semantics of the queries . a concept network is adopted as the knowledge base to represent the relevance of the concepts . the concept network is explored from the www . moreover , they also support neighborhood queries , which retrieve documents relevant to a document specified by a user .",
        "finding clusters in data is a challenging problem . given a dataset , we usually do not know the number of natural clusters hidden in the dataset . the problem is exacerbated when there is little or no additional information except the data itself . this paper proposes a general stochastic clustering method that is a simplification of nature-inspired ant-based clustering approach . it begins with a basic solution and then performs stochastic search to incrementally improve the solution until the underlying clusters this method differs from several recent methods in that it does not require users to input the number of clusters our experimental results show that the proposed method performs better than several existing methods in terms of clustering accuracy and our theoretical analysis shows that the proposed method has linear time and space complexities , and our empirical study shows",
        "engineers are becoming more aware of the usefulness of convolution in solving engineering problems . the methods used to explain and motivate convolution in the past are not adequate to unk in the student the this paper poses the problems associated with the present teaching methods and suggests other approaches and examples which can be"


        )
        val spinner2=findViewById<Spinner>(R.id.spinner2)
        if(spinner2!=null){
            val arrayAdapter = ArrayAdapter(this, android.R.layout.simple_spinner_item, personName)
            spinner2.adapter = arrayAdapter

            spinner2.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
                override fun onItemSelected(parent: AdapterView<*>, view: View, position: Int, id: Long) {
                    Toast.makeText(this@Recommendation, getString(R.string.selected_item) + " " + personName[position], Toast.LENGTH_SHORT).show()
                }

                override fun onNothingSelected(parent: AdapterView<*>) {
                    // Code to perform some action when nothing is selected
                }
            }
        }
        show_recommendations.setOnClickListener {
            val intent= Intent(this,ResultActivity::class.java)
            startActivity(intent)
        }



    }


}